# Generated by Django 4.2.1 on 2023-05-05 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="address",
            name="order",
            field=models.OneToOneField(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.order"
            ),
            preserve_default=False,
        ),
    ]
