# Generated by Django 4.2 on 2023-05-01 16:50

from django.db import migrations
import imagekit.models.fields
import tree.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                default="category/default.png", upload_to=tree.utils.hashed_filename
            ),
        ),
    ]
