# Generated by Django 4.2 on 2023-04-25 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_product_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="product",
            name="summary",
            field=models.TextField(default=""),
        ),
    ]
