# Generated by Django 4.2.1 on 2023-05-09 07:53

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_remove_order_address_address_order"),
    ]

    operations = [
        UnaccentExtension(),
    ]
