# Generated by Django 4.2 on 2023-04-29 01:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0003_product_description_alter_product_summary"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                default="admin",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                to_field="username",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="state",
            field=models.CharField(
                choices=[
                    ("PE", "Chưa xác nhận"),
                    ("DE", "Đang giao"),
                    ("CO", "Hoàn thành"),
                    ("CA", "Đã hủy"),
                ],
                default="PE",
                max_length=2,
            ),
        ),
    ]
