# Generated by Django 4.2 on 2023-05-03 12:20

from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tree.utils


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_remove_product_category_product_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="image",
            field=imagekit.models.fields.ProcessedImageField(
                default="defaults/category.png", upload_to=tree.utils.hashed_filename
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="core.category"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="thumbnail",
            field=imagekit.models.fields.ProcessedImageField(
                default="defaults/product.png", upload_to=tree.utils.hashed_filename
            ),
        ),
    ]
