# Generated by Django 4.2.1 on 2023-05-09 15:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_order_delivery_fee_alter_order_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="delivery_fee",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="total",
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
