# Generated by Django 4.2.1 on 2023-05-09 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_alter_order_delivery_fee_alter_order_total"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="order",
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="core.address",
            ),
        ),
    ]
