# Generated by Django 4.2.1 on 2023-05-09 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_order_items_alter_orderitem_order"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="address",
            new_name="address1",
        ),
        migrations.RemoveField(
            model_name="address",
            name="ward",
        ),
        migrations.AddField(
            model_name="address",
            name="address2",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
