# Generated by Django 4.2.1 on 2023-05-04 19:10

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_product_name_alter_product_unique_together"),
    ]

    operations = [UnaccentExtension()]
