# Generated by Django 4.2.1 on 2023-05-05 08:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_district_province_ward_district_province"),
    ]

    operations = [
        migrations.AddField(
            model_name="district",
            name="code",
            field=models.CharField(default="-1", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="province",
            name="code",
            field=models.CharField(default="-1", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="ward",
            name="code",
            field=models.CharField(default="-1", max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="ward",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
