# Generated by Django 4.2.1 on 2023-05-05 09:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_district_code_province_code_ward_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="district",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="district",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="province",
            name="code",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="province",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("name", "code", "province")},
        ),
        migrations.AlterUniqueTogether(
            name="province",
            unique_together={("name", "code")},
        ),
        migrations.AlterUniqueTogether(
            name="ward",
            unique_together={("name", "code", "district")},
        ),
    ]
