# Generated by Django 4.2.1 on 2023-05-05 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0013_alter_ward_code_alter_ward_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="ward",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="core.ward"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(through="core.OrderItem", to="core.product"),
        ),
    ]
