# Generated by Django 4.2.1 on 2023-05-05 22:17

from django.db import migrations, models
import imagekit.models.fields
import markdownx.models
import tree.utils


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "cover_image",
                    imagekit.models.fields.ProcessedImageField(
                        default="posts/default.jpg",
                        upload_to=tree.utils.hashed_filename,
                    ),
                ),
                ("content", markdownx.models.MarkdownxField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
