# Generated by Django 4.2.1 on 2023-05-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[("blog", "Blog"), ("bug", "Bug Report")],
                default="blog",
                max_length=10,
            ),
        ),
    ]
