# Generated by Django 4.1.7 on 2023-04-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_delete_mymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image',
            field=models.ImageField(default='media/authetic.jpg', upload_to='media/'),
            preserve_default=False,
        ),
    ]
