# Generated by Django 4.2 on 2023-05-01 16:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_delete_mymodel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="summary",
        ),
    ]
