# Generated by Django 4.2.1 on 2023-06-28 12:39

from django.db import migrations
import imagekit.models.fields
import tree.utils


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_post_post_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="cover_image",
            field=imagekit.models.fields.ProcessedImageField(
                default="defaults/post.jpg", upload_to=tree.utils.hashed_filename
            ),
        ),
    ]
