# Generated by Django 4.2 on 2023-04-05 08:18

import blog.models
from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cover_image',
            field=imagekit.models.fields.ProcessedImageField(default='posts/default.jpg', upload_to=blog.models.Post.get_path),
        ),
    ]
