# Generated by Django 4.2 on 2023-04-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_post_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="summary",
            field=models.CharField(default="", max_length=200),
        ),
    ]
