# Generated by Django 4.2 on 2023-04-28 00:40

from django.db import migrations
import markdownx.models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_post_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="content",
            field=markdownx.models.MarkdownxField(),
        ),
    ]
