# Generated by Django 4.2 on 2023-05-03 12:20

from django.db import migrations
import imagekit.models.fields
import tree.utils


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=imagekit.models.fields.ProcessedImageField(
                default="defaults/avatar.png", upload_to=tree.utils.hashed_filename
            ),
        ),
    ]
